import React, { useState } from 'react';
import { FournisseurEtablissement, SelecteurEtablissement, useEtablissement } from './noyau/ContexteEtablissement.jsx';
import { GardePermission } from './noyau/GardePermission.jsx';
import { clientsDemo, equipeDemo, etablissementsDemo, membreDemo, utilisateurDemo } from './demo/donnees.js';

const onglets = ['tableau_de_bord', 'identite', 'parametres', 'membres', 'editeur'];
function Pastille({ children, ton = 'vert' }) { return <span className={`pastille ${ton}`}>{children}</span>; }
function TableauDeBord({ etablissement }) { return <div className="grille"><article className="carte vedette"><p>Établissement actif</p><strong>{etablissement.ville}</strong><small>3 modules du socle disponibles</small></article><article className="carte"><p>Équipe</p><strong>{equipeDemo.length}</strong><small>membres et invitations</small></article><article className="carte"><p>Sécurité</p><strong>Protégé</strong><small>Isolation par établissement active</small></article></div>; }
function Identite({ etablissement }) { return <section className="panneau"><div><p className="sur-titre sombre">IDENTITÉ</p><h2>Informations publiques</h2></div><form><label>Nom commercial<input defaultValue={etablissement.nom}/></label><label>Ville<input defaultValue={etablissement.ville}/></label><label>Devise<input defaultValue="XAF"/></label><label>Couleur principale<input type="color" defaultValue="#173c31"/></label><button type="button">Enregistrer la démo</button></form></section>; }
function Parametres() { return <section className="panneau"><div><p className="sur-titre sombre">PARAMÈTRES</p><h2>Configuration locale</h2></div><div className="liste"><div><strong>Langue</strong><span>Français</span></div><div><strong>Fuseau horaire</strong><span>Africa/Brazzaville</span></div><div><strong>Numérotation</strong><span>Préfixe ME</span></div></div></section>; }
function Membres() { return <section className="panneau"><div className="titre-ligne"><div><p className="sur-titre sombre">MEMBRES ET RÔLES</p><h2>L’équipe de l’établissement</h2></div><button>Inviter</button></div><div className="table" role="table">{equipeDemo.map((personne) => <div className="ligne" role="row" key={personne.nom}><span className="avatar">{personne.initiales}</span><strong>{personne.nom}</strong><span>{personne.role}</span><Pastille ton={personne.statut === 'Invitée' ? 'or' : 'vert'}>{personne.statut}</Pastille></div>)}</div></section>; }
function Editeur() { return <section className="panneau"><div><p className="sur-titre sombre">ESPACE ÉDITEUR</p><h2>Clients et établissements</h2></div><div className="table" role="table">{clientsDemo.map((client) => <div className="ligne client" role="row" key={client.nom}><strong>{client.nom}</strong><span>{client.etablissements} établissement(s)</span><Pastille ton={client.statut === 'Suspendu' ? 'or' : 'vert'}>{client.statut}</Pastille><button>Détails</button></div>)}</div><h3>Modules proposés</h3><div className="modules"><Pastille>Établissement</Pastille><Pastille>Membres</Pastille><Pastille>Tableau de bord</Pastille></div></section>; }
function Contenu({ page, etablissement }) { if (page === 'identite') return <Identite etablissement={etablissement}/>; if (page === 'parametres') return <Parametres/>; if (page === 'membres') return <Membres/>; if (page === 'editeur') return <Editeur/>; return <TableauDeBord etablissement={etablissement}/>; }
function Espace() {
  const { etablissement } = useEtablissement(); const [page, setPage] = useState('tableau_de_bord');
  return <main><header><button className="logo" onClick={() => setPage('tableau_de_bord')}><span>AE</span><b>AGENCE ELITE</b></button><span>{utilisateurDemo.nom} · {utilisateurDemo.role}</span></header><section className="hero"><p className="sur-titre">ESPACE DE GESTION</p><h1>{etablissement.nom}</h1><SelecteurEtablissement etablissements={etablissementsDemo}/></section><nav>{onglets.filter((id) => id !== 'membres' || etablissement.modules.includes('membres')).map((id) => <button className={page === id ? 'actif' : ''} key={id} onClick={() => setPage(id)}>{id.replaceAll('_', ' ')}</button>)}</nav><GardePermission membre={membreDemo} permission="tableau_de_bord.lire" modulesActives={etablissement.modules} sinon={<p>Accès non autorisé</p>}><Contenu page={page} etablissement={etablissement}/></GardePermission><footer>Environnement local · démonstration fictive · aucune donnée réelle</footer></main>;
}
export default function App() { return <FournisseurEtablissement etablissements={etablissementsDemo}><Espace/></FournisseurEtablissement>; }
