-- Audit 013 : index de soutien des clés étrangères après reconstruction complète.
-- Ne modifie aucune donnée ; les index sont créés uniquement s’ils sont absents.
-- Le déploiement nécessite sauvegarde, simulation et validation des volumes en production.
create index if not exists audit_fk_abo_formules_article_id on public.abo_formules (article_id);
create index if not exists audit_fk_abonnement_periodes_etablissement_id on public.abonnement_periodes (etablissement_id);
create index if not exists audit_fk_abonnements_contact_id on public.abonnements (contact_id);
create index if not exists audit_fk_abonnements_cree_par on public.abonnements (cree_par);
create index if not exists audit_fk_abonnements_formule_id on public.abonnements (formule_id);
create index if not exists audit_fk_agenda_rendez_vous_article_id on public.agenda_rendez_vous (article_id);
create index if not exists audit_fk_agenda_rendez_vous_contact_id on public.agenda_rendez_vous (contact_id);
create index if not exists audit_fk_agenda_rendez_vous_cree_par on public.agenda_rendez_vous (cree_par);
create index if not exists audit_fk_agenda_rendez_vous_document_id on public.agenda_rendez_vous (document_id);
create index if not exists audit_fk_agenda_rendez_vous_opportunite_id_etablissement_id on public.agenda_rendez_vous (opportunite_id, etablissement_id);
create index if not exists audit_fk_boutique_articles_etablissement_id on public.boutique_articles (etablissement_id);
create index if not exists audit_fk_boutique_commandes_contact_id on public.boutique_commandes (contact_id);
create index if not exists audit_fk_boutique_commandes_coupon_id on public.boutique_commandes (coupon_id);
create index if not exists audit_fk_boutique_commandes_hub_id_etablissement_id on public.boutique_commandes (hub_id, etablissement_id);
create index if not exists audit_fk_boutique_commandes_traitee_par on public.boutique_commandes (traitee_par);
create index if not exists audit_fk_boutique_commandes_vente_id on public.boutique_commandes (vente_id);
create index if not exists audit_fk_boutique_lignes_article_id on public.boutique_lignes (article_id);
create index if not exists audit_fk_boutique_lignes_etablissement_id on public.boutique_lignes (etablissement_id);
create index if not exists audit_fk_boutiques_hub_id_etablissement_id on public.boutiques (hub_id, etablissement_id);
create index if not exists audit_fk_clotures_cloturee_par on public.clotures (cloturee_par);
create index if not exists audit_fk_clotures_hub_id_etablissement_id on public.clotures (hub_id, etablissement_id);
create index if not exists audit_fk_clotures_point_de_vente_id on public.clotures (point_de_vente_id);
create index if not exists audit_fk_commandes_achat_annulee_par on public.commandes_achat (annulee_par);
create index if not exists audit_fk_commandes_achat_cree_par on public.commandes_achat (cree_par);
create index if not exists audit_fk_commandes_achat_demande_par on public.commandes_achat (demande_par);
create index if not exists audit_fk_commandes_achat_hub_id_etablissement_id on public.commandes_achat (hub_id, etablissement_id);
create index if not exists audit_fk_comptes_connexion_cree_par on public.comptes_connexion (cree_par);
create index if not exists audit_fk_contacts_responsable_id on public.contacts (responsable_id);
create index if not exists audit_fk_crm_activites_cree_par on public.crm_activites (cree_par);
create index if not exists audit_fk_crm_activites_opportunite_id_etablissement_id on public.crm_activites (opportunite_id, etablissement_id);
create index if not exists audit_fk_crm_opportunites_cree_par on public.crm_opportunites (cree_par);
create index if not exists audit_fk_crm_opportunites_document_vente_id on public.crm_opportunites (document_vente_id);
create index if not exists audit_fk_crm_opportunites_etape_id_etablissement_id on public.crm_opportunites (etape_id, etablissement_id);
create index if not exists audit_fk_depenses_annulee_par on public.depenses (annulee_par);
create index if not exists audit_fk_depenses_cree_par on public.depenses (cree_par);
create index if not exists audit_fk_depenses_hub_id_etablissement_id on public.depenses (hub_id, etablissement_id);
create index if not exists audit_fk_documents_dossiers_cree_par on public.documents_dossiers (cree_par);
create index if not exists audit_fk_documents_vente_annule_par on public.documents_vente (annule_par);
create index if not exists audit_fk_documents_vente_cree_par on public.documents_vente (cree_par);
create index if not exists audit_fk_documents_vente_emis_par on public.documents_vente (emis_par);
create index if not exists audit_fk_documents_vente_hub_id_etablissement_id on public.documents_vente (hub_id, etablissement_id);
create index if not exists audit_fk_fidelite_attributions_attribue_par on public.fidelite_attributions (attribue_par);
create index if not exists audit_fk_fidelite_attributions_contact_id on public.fidelite_attributions (contact_id);
create index if not exists audit_fk_fidelite_attributions_recompense_id on public.fidelite_attributions (recompense_id);
create index if not exists audit_fk_fidelite_attributions_vente_id on public.fidelite_attributions (vente_id);
create index if not exists audit_fk_fidelite_mouvements_contact_id on public.fidelite_mouvements (contact_id);
create index if not exists audit_fk_fidelite_mouvements_cree_par on public.fidelite_mouvements (cree_par);
create index if not exists audit_fk_fidelite_mouvements_vente_id on public.fidelite_mouvements (vente_id);
create index if not exists audit_fk_hotel_chambres_type_id_etablissement_id on public.hotel_chambres (type_id, etablissement_id);
create index if not exists audit_fk_hotel_prestations_annule_par on public.hotel_prestations (annule_par);
create index if not exists audit_fk_hotel_prestations_article_id on public.hotel_prestations (article_id);
create index if not exists audit_fk_hotel_prestations_etablissement_id on public.hotel_prestations (etablissement_id);
create index if not exists audit_fk_hotel_prestations_reservation_id_etablissement_id on public.hotel_prestations (reservation_id, etablissement_id);
create index if not exists audit_fk_hotel_prestations_saisi_par on public.hotel_prestations (saisi_par);
create index if not exists audit_fk_hotel_reservations_chambre_id_etablissement_id on public.hotel_reservations (chambre_id, etablissement_id);
create index if not exists audit_fk_hotel_reservations_contact_id on public.hotel_reservations (contact_id);
create index if not exists audit_fk_hotel_reservations_cree_par on public.hotel_reservations (cree_par);
create index if not exists audit_fk_hotel_reservations_document_vente_id on public.hotel_reservations (document_vente_id);
create index if not exists audit_fk_hotel_reservations_type_id_etablissement_id on public.hotel_reservations (type_id, etablissement_id);
create index if not exists audit_fk_inventaires_auteur on public.inventaires (auteur);
create index if not exists audit_fk_inventaires_hub_id_etablissement_id on public.inventaires (hub_id, etablissement_id);
create index if not exists audit_fk_lignes_commande_achat_commande_id_etablissement_id on public.lignes_commande_achat (commande_id, etablissement_id);
create index if not exists audit_fk_lignes_commande_achat_etablissement_id on public.lignes_commande_achat (etablissement_id);
create index if not exists audit_fk_lignes_document_vente_document_id_etablissement_id on public.lignes_document_vente (document_id, etablissement_id);
create index if not exists audit_fk_lignes_document_vente_etablissement_id on public.lignes_document_vente (etablissement_id);
create index if not exists audit_fk_lignes_inventaire_etablissement_id on public.lignes_inventaire (etablissement_id);
create index if not exists audit_fk_lignes_reception_achat_article_id on public.lignes_reception_achat (article_id);
create index if not exists audit_fk_lignes_reception_achat_etablissement_id on public.lignes_reception_achat (etablissement_id);
create index if not exists audit_fk_lignes_reception_achat_ligne_commande_id on public.lignes_reception_achat (ligne_commande_id);
create index if not exists audit_fk_lignes_reception_achat_reception_id_etablissement_id on public.lignes_reception_achat (reception_id, etablissement_id);
create index if not exists audit_fk_lignes_retour_vente_article_id on public.lignes_retour_vente (article_id);
create index if not exists audit_fk_lignes_retour_vente_hub_id on public.lignes_retour_vente (hub_id);
create index if not exists audit_fk_lignes_transfert_etablissement_id on public.lignes_transfert (etablissement_id);
create index if not exists audit_fk_membre_hubs_cree_par on public.membre_hubs (cree_par);
create index if not exists audit_fk_membre_hubs_hub_id_etablissement_id on public.membre_hubs (hub_id, etablissement_id);
create index if not exists audit_fk_modules_categorie on public.modules (categorie);
create index if not exists audit_fk_mouvements_stock_acteur on public.mouvements_stock (acteur);
create index if not exists audit_fk_mouvements_stock_hub_id_etablissement_id on public.mouvements_stock (hub_id, etablissement_id);
create index if not exists audit_fk_mouvements_stock_inventaire_id on public.mouvements_stock (inventaire_id);
create index if not exists audit_fk_mouvements_stock_reception_id on public.mouvements_stock (reception_id);
create index if not exists audit_fk_mouvements_stock_transfert_id on public.mouvements_stock (transfert_id);
create index if not exists audit_fk_offres_solution_id on public.offres (solution_id);
create index if not exists audit_fk_pages_auth_brouillon_modifie_par on public.pages_auth (brouillon_modifie_par);
create index if not exists audit_fk_pages_auth_client_id on public.pages_auth (client_id);
create index if not exists audit_fk_pages_auth_etablissement_id on public.pages_auth (etablissement_id);
create index if not exists audit_fk_pages_auth_publie_par on public.pages_auth (publie_par);
create index if not exists audit_fk_pages_auth_journal_auteur on public.pages_auth_journal (auteur);
create index if not exists audit_fk_paiements_annule_par on public.paiements (annule_par);
create index if not exists audit_fk_paiements_encaisse_par on public.paiements (encaisse_par);
create index if not exists audit_fk_paiements_hub_id_etablissement_id on public.paiements (hub_id, etablissement_id);
create index if not exists audit_fk_paiements_fournisseur_annule_par on public.paiements_fournisseur (annule_par);
create index if not exists audit_fk_paiements_fournisseur_commande_id_etablissement_id on public.paiements_fournisseur (commande_id, etablissement_id);
create index if not exists audit_fk_paiements_fournisseur_etablissement_id on public.paiements_fournisseur (etablissement_id);
create index if not exists audit_fk_paiements_fournisseur_paye_par on public.paiements_fournisseur (paye_par);
create index if not exists audit_fk_pieces_jointes_ajoute_par on public.pieces_jointes (ajoute_par);
create index if not exists audit_fk_pieces_jointes_archivee_par on public.pieces_jointes (archivee_par);
create index if not exists audit_fk_points_de_vente_hub_id_etablissement_id on public.points_de_vente (hub_id, etablissement_id);
create index if not exists audit_fk_projet_taches_cree_par on public.projet_taches (cree_par);
create index if not exists audit_fk_projet_taches_etablissement_id on public.projet_taches (etablissement_id);
create index if not exists audit_fk_projet_taches_projet_id_etablissement_id on public.projet_taches (projet_id, etablissement_id);
create index if not exists audit_fk_projet_temps_annule_par on public.projet_temps (annule_par);
create index if not exists audit_fk_projet_temps_document_vente_id on public.projet_temps (document_vente_id);
create index if not exists audit_fk_projet_temps_etablissement_id on public.projet_temps (etablissement_id);
create index if not exists audit_fk_projet_temps_projet_id_etablissement_id on public.projet_temps (projet_id, etablissement_id);
create index if not exists audit_fk_projet_temps_saisi_par on public.projet_temps (saisi_par);
create index if not exists audit_fk_projet_temps_tache_id_etablissement_id on public.projet_temps (tache_id, etablissement_id);
create index if not exists audit_fk_projets_contact_id on public.projets (contact_id);
create index if not exists audit_fk_projets_cree_par on public.projets (cree_par);
create index if not exists audit_fk_projets_opportunite_id on public.projets (opportunite_id);
create index if not exists audit_fk_projets_responsable_id on public.projets (responsable_id);
create index if not exists audit_fk_receptions_achat_commande_id_etablissement_id on public.receptions_achat (commande_id, etablissement_id);
create index if not exists audit_fk_receptions_achat_hub_id_etablissement_id on public.receptions_achat (hub_id, etablissement_id);
create index if not exists audit_fk_receptions_achat_recue_par on public.receptions_achat (recue_par);
create index if not exists audit_fk_remboursements_vente_hub_id on public.remboursements_vente (hub_id);
create index if not exists audit_fk_remboursements_vente_rembourse_par on public.remboursements_vente (rembourse_par);
create index if not exists audit_fk_rest_affectations_affectee_par on public.rest_affectations (affectee_par);
create index if not exists audit_fk_rest_affectations_hub_id_etablissement_id on public.rest_affectations (hub_id, etablissement_id);
create index if not exists audit_fk_rest_affectations_serveur_id on public.rest_affectations (serveur_id);
create index if not exists audit_fk_rest_affectations_table_id_etablissement_id on public.rest_affectations (table_id, etablissement_id);
create index if not exists audit_fk_rest_affectations_terminee_par on public.rest_affectations (terminee_par);
create index if not exists audit_fk_rest_commandes_hub_id_etablissement_id on public.rest_commandes (hub_id, etablissement_id);
create index if not exists audit_fk_rest_commandes_pris_par on public.rest_commandes (pris_par);
create index if not exists audit_fk_rest_commandes_serveur_id on public.rest_commandes (serveur_id);
create index if not exists audit_fk_rest_commandes_table_id_etablissement_id on public.rest_commandes (table_id, etablissement_id);
create index if not exists audit_fk_rest_lignes_ajoutee_par on public.rest_lignes (ajoutee_par);
create index if not exists audit_fk_rest_lignes_annulee_par on public.rest_lignes (annulee_par);
create index if not exists audit_fk_rest_lignes_article_id on public.rest_lignes (article_id);
create index if not exists audit_fk_rest_lignes_commande_id_etablissement_id on public.rest_lignes (commande_id, etablissement_id);
create index if not exists audit_fk_rest_lignes_etablissement_id on public.rest_lignes (etablissement_id);
create index if not exists audit_fk_rest_reservations_contact_id on public.rest_reservations (contact_id);
create index if not exists audit_fk_rest_reservations_cree_par on public.rest_reservations (cree_par);
create index if not exists audit_fk_rest_reservations_hub_id on public.rest_reservations (hub_id);
create index if not exists audit_fk_rest_reservations_table_id on public.rest_reservations (table_id);
create index if not exists audit_fk_rest_transferts_serveur_ancien_serveur_id on public.rest_transferts_serveur (ancien_serveur_id);
create index if not exists audit_fk_rest_transferts_serveur_commande_id_etablissement_id on public.rest_transferts_serveur (commande_id, etablissement_id);
create index if not exists audit_fk_rest_transferts_serveur_etablissement_id on public.rest_transferts_serveur (etablissement_id);
create index if not exists audit_fk_rest_transferts_serveur_nouveau_serveur_id on public.rest_transferts_serveur (nouveau_serveur_id);
create index if not exists audit_fk_rest_transferts_serveur_transfere_par on public.rest_transferts_serveur (transfere_par);
create index if not exists audit_fk_retours_vente_cree_par on public.retours_vente (cree_par);
create index if not exists audit_fk_retours_vente_hub_id on public.retours_vente (hub_id);
create index if not exists audit_fk_rh_absences_annulee_par on public.rh_absences (annulee_par);
create index if not exists audit_fk_rh_absences_decidee_par on public.rh_absences (decidee_par);
create index if not exists audit_fk_rh_absences_demandee_par on public.rh_absences (demandee_par);
create index if not exists audit_fk_rh_absences_employe_id_etablissement_id on public.rh_absences (employe_id, etablissement_id);
create index if not exists audit_fk_rh_ajustements_conges_auteur on public.rh_ajustements_conges (auteur);
create index if not exists audit_fk_rh_ajustements_conges_employe_id_etablissement_id on public.rh_ajustements_conges (employe_id, etablissement_id);
create index if not exists audit_fk_rh_ajustements_conges_etablissement_id on public.rh_ajustements_conges (etablissement_id);
create index if not exists audit_fk_rh_contrats_cree_par on public.rh_contrats (cree_par);
create index if not exists audit_fk_rh_contrats_employe_id_etablissement_id on public.rh_contrats (employe_id, etablissement_id);
create index if not exists audit_fk_rh_contrats_poste_id_etablissement_id on public.rh_contrats (poste_id, etablissement_id);
create index if not exists audit_fk_rh_creneaux_cree_par on public.rh_creneaux (cree_par);
create index if not exists audit_fk_rh_creneaux_employe_id_etablissement_id on public.rh_creneaux (employe_id, etablissement_id);
create index if not exists audit_fk_rh_creneaux_hub_id_etablissement_id on public.rh_creneaux (hub_id, etablissement_id);
create index if not exists audit_fk_rh_departements_parent_id_etablissement_id on public.rh_departements (parent_id, etablissement_id);
create index if not exists audit_fk_rh_departements_responsable_id_etablissement_id on public.rh_departements (responsable_id, etablissement_id);
create index if not exists audit_fk_rh_employes_departement_id_etablissement_id on public.rh_employes (departement_id, etablissement_id);
create index if not exists audit_fk_rh_employes_horaire_id_etablissement_id on public.rh_employes (horaire_id, etablissement_id);
create index if not exists audit_fk_rh_employes_hub_id_etablissement_id on public.rh_employes (hub_id, etablissement_id);
create index if not exists audit_fk_rh_employes_manager_id_etablissement_id on public.rh_employes (manager_id, etablissement_id);
create index if not exists audit_fk_rh_employes_poste_id_etablissement_id on public.rh_employes (poste_id, etablissement_id);
create index if not exists audit_fk_rh_employes_prives_employe_id_etablissement_id on public.rh_employes_prives (employe_id, etablissement_id);
create index if not exists audit_fk_rh_employes_prives_etablissement_id on public.rh_employes_prives (etablissement_id);
create index if not exists audit_fk_rh_pointages_cree_par on public.rh_pointages (cree_par);
create index if not exists audit_fk_rh_pointages_employe_id_etablissement_id on public.rh_pointages (employe_id, etablissement_id);
create index if not exists audit_fk_rh_pointages_hub_id_etablissement_id on public.rh_pointages (hub_id, etablissement_id);
create index if not exists audit_fk_rh_postes_departement_id_etablissement_id on public.rh_postes (departement_id, etablissement_id);
create index if not exists audit_fk_sessions_caisse_hub_id_etablissement_id on public.sessions_caisse (hub_id, etablissement_id);
create index if not exists audit_fk_sessions_caisse_ouverte_par on public.sessions_caisse (ouverte_par);
create index if not exists audit_fk_sessions_caisse_point_de_vente_id on public.sessions_caisse (point_de_vente_id);
create index if not exists audit_fk_site_messages_page_id on public.site_messages (page_id);
create index if not exists audit_fk_site_messages_traite_par on public.site_messages (traite_par);
create index if not exists audit_fk_site_pages_publiee_par on public.site_pages (publiee_par);
create index if not exists audit_fk_support_messages_auteur on public.support_messages (auteur);
create index if not exists audit_fk_support_messages_etablissement_id on public.support_messages (etablissement_id);
create index if not exists audit_fk_support_tickets_assigne_a on public.support_tickets (assigne_a);
create index if not exists audit_fk_support_tickets_contact_id on public.support_tickets (contact_id);
create index if not exists audit_fk_support_tickets_cree_par on public.support_tickets (cree_par);
create index if not exists audit_fk_support_tickets_vente_id on public.support_tickets (vente_id);
create index if not exists audit_fk_transferts_annule_par on public.transferts (annule_par);
create index if not exists audit_fk_transferts_auteur on public.transferts (auteur);
create index if not exists audit_fk_transferts_hub_destination_id_etablissement_id on public.transferts (hub_destination_id, etablissement_id);
create index if not exists audit_fk_transferts_hub_source_id_etablissement_id on public.transferts (hub_source_id, etablissement_id);
create index if not exists audit_fk_types_pieces_jointes_module_id on public.types_pieces_jointes (module_id);
create index if not exists audit_fk_types_pieces_jointes_permission_ecrire on public.types_pieces_jointes (permission_ecrire);
create index if not exists audit_fk_types_pieces_jointes_permission_lire on public.types_pieces_jointes (permission_lire);
create index if not exists audit_fk_ventes_annulee_par on public.ventes (annulee_par);
create index if not exists audit_fk_ventes_hub_id_etablissement_id on public.ventes (hub_id, etablissement_id);
create index if not exists audit_fk_ventes_point_de_vente_id on public.ventes (point_de_vente_id);
create index if not exists audit_fk_ventes_vendeur on public.ventes (vendeur);
