// Catalogues de départ par métier (« Partir d'un modèle ») : noms génériques, sans marque, prix vides à compléter.
// Chaque article : [nom, unité de vente, catégorie]. Les unités reprennent les valeurs de saisieRapide.js (UNITES).
// Pharmacie / parapharmacie : uniquement des produits d'hygiène et du petit matériel, jamais de médicament.

const liste = (articles) => articles.map(([nom, unite, categorie]) => ({ nom, unite, categorie }));

export const MODELES = [
  {
    id: 'epicerie',
    libelle: 'Épicerie / alimentation',
    articles: liste([
      ['Riz', 'kg', 'Céréales et féculents'],
      ['Riz (sac de 25 kg)', 'sac', 'Céréales et féculents'],
      ['Farine de blé', 'kg', 'Céréales et féculents'],
      ['Semoule de maïs', 'kg', 'Céréales et féculents'],
      ['Foufou (farine de manioc)', 'kg', 'Céréales et féculents'],
      ['Pâtes spaghetti', 'paquet', 'Céréales et féculents'],
      ['Macaronis', 'paquet', 'Céréales et féculents'],
      ['Pain', 'unité', 'Céréales et féculents'],
      ['Haricots secs', 'kg', 'Céréales et féculents'],
      ['Sucre en poudre', 'kg', 'Épicerie'],
      ['Sucre en morceaux', 'boîte', 'Épicerie'],
      ['Sel', 'sachet', 'Épicerie'],
      ['Huile végétale', 'L', 'Épicerie'],
      ['Huile de palme', 'L', 'Épicerie'],
      ['Concentré de tomate', 'boîte', 'Épicerie'],
      ['Bouillon en cubes', 'paquet', 'Épicerie'],
      ['Piment séché', 'sachet', 'Épicerie'],
      ['Vinaigre', 'bouteille', 'Épicerie'],
      ['Mayonnaise', 'unité', 'Épicerie'],
      ['Café moulu', 'paquet', 'Épicerie'],
      ['Thé en sachets', 'boîte', 'Épicerie'],
      ['Chocolat en poudre', 'boîte', 'Épicerie'],
      ['Biscuits', 'paquet', 'Épicerie'],
      ['Levure boulangère', 'sachet', 'Épicerie'],
      ['Arachides', 'kg', 'Épicerie'],
      ['Lait en poudre', 'boîte', 'Produits laitiers'],
      ['Lait concentré sucré', 'boîte', 'Produits laitiers'],
      ['Margarine', 'boîte', 'Produits laitiers'],
      ['Yaourt', 'unité', 'Produits laitiers'],
      ['Œufs', 'unité', 'Produits laitiers'],
      ['Sardines à l’huile', 'boîte', 'Conserves'],
      ['Thon en conserve', 'boîte', 'Conserves'],
      ['Corned-beef', 'boîte', 'Conserves'],
      ['Oignons', 'kg', 'Fruits et légumes'],
      ['Ail', 'unité', 'Fruits et légumes'],
      ['Pommes de terre', 'kg', 'Fruits et légumes'],
      ['Tomates', 'kg', 'Fruits et légumes'],
      ['Bananes plantains', 'tas', 'Fruits et légumes'],
      ['Viande de bœuf', 'kg', 'Viandes et poissons'],
      ['Poulet congelé', 'kg', 'Viandes et poissons'],
      ['Cuisses de poulet', 'kg', 'Viandes et poissons'],
      ['Poisson salé', 'kg', 'Viandes et poissons'],
      ['Poisson fumé', 'kg', 'Viandes et poissons'],
      ['Eau minérale 1,5 L', 'bouteille', 'Boissons'],
      ['Savon de ménage', 'unité', 'Hygiène et entretien'],
      ['Lessive en poudre', 'sachet', 'Hygiène et entretien'],
      ['Papier toilette', 'rouleau', 'Hygiène et entretien'],
      ['Allumettes', 'boîte', 'Hygiène et entretien'],
      ['Bougies', 'paquet', 'Hygiène et entretien'],
    ]),
  },
  {
    id: 'boissons',
    libelle: 'Boissons / bar',
    articles: liste([
      ['Eau minérale 50 cl', 'bouteille', 'Eaux'],
      ['Eau minérale 1,5 L', 'bouteille', 'Eaux'],
      ['Eau gazeuse', 'bouteille', 'Eaux'],
      ['Bière blonde 65 cl', 'bouteille', 'Bières'],
      ['Bière blonde 33 cl', 'bouteille', 'Bières'],
      ['Bière brune 65 cl', 'bouteille', 'Bières'],
      ['Bière en canette', 'unité', 'Bières'],
      ['Bière sans alcool', 'bouteille', 'Bières'],
      ['Soda cola 33 cl', 'bouteille', 'Sodas et jus'],
      ['Soda orange 33 cl', 'bouteille', 'Sodas et jus'],
      ['Soda citron 33 cl', 'bouteille', 'Sodas et jus'],
      ['Limonade', 'bouteille', 'Sodas et jus'],
      ['Tonic', 'bouteille', 'Sodas et jus'],
      ['Boisson énergisante', 'unité', 'Sodas et jus'],
      ['Jus d’orange', 'bouteille', 'Sodas et jus'],
      ['Jus d’ananas', 'bouteille', 'Sodas et jus'],
      ['Jus de gingembre', 'bouteille', 'Sodas et jus'],
      ['Jus de bissap', 'bouteille', 'Sodas et jus'],
      ['Jus de fruits pressé', 'verre', 'Sodas et jus'],
      ['Vin rouge', 'bouteille', 'Vins'],
      ['Vin rouge (verre)', 'verre', 'Vins'],
      ['Vin blanc', 'bouteille', 'Vins'],
      ['Vin rosé', 'bouteille', 'Vins'],
      ['Vin mousseux', 'bouteille', 'Vins'],
      ['Vin de palme', 'L', 'Vins'],
      ['Whisky (verre)', 'verre', 'Alcools forts'],
      ['Whisky (bouteille)', 'bouteille', 'Alcools forts'],
      ['Vodka', 'verre', 'Alcools forts'],
      ['Rhum', 'verre', 'Alcools forts'],
      ['Gin', 'verre', 'Alcools forts'],
      ['Liqueur', 'verre', 'Alcools forts'],
      ['Pastis', 'verre', 'Alcools forts'],
      ['Cocktail maison', 'verre', 'Cocktails'],
      ['Cocktail sans alcool', 'verre', 'Cocktails'],
      ['Café', 'unité', 'Boissons chaudes'],
      ['Thé', 'unité', 'Boissons chaudes'],
      ['Chocolat chaud', 'unité', 'Boissons chaudes'],
      ['Glaçons', 'sachet', 'Divers'],
      ['Cacahuètes grillées', 'sachet', 'Divers'],
    ]),
  },
  {
    id: 'quincaillerie',
    libelle: 'Quincaillerie',
    articles: liste([
      ['Ciment (sac de 50 kg)', 'sac', 'Maçonnerie'],
      ['Fer à béton', 'unité', 'Maçonnerie'],
      ['Fil de fer recuit', 'kg', 'Maçonnerie'],
      ['Truelle', 'unité', 'Maçonnerie'],
      ['Pelle', 'unité', 'Maçonnerie'],
      ['Brouette', 'unité', 'Maçonnerie'],
      ['Seau', 'unité', 'Maçonnerie'],
      ['Clous', 'kg', 'Fixations'],
      ['Clous pour tôle', 'kg', 'Fixations'],
      ['Vis à bois', 'boîte', 'Fixations'],
      ['Chevilles', 'sachet', 'Fixations'],
      ['Boulons', 'unité', 'Fixations'],
      ['Tôle ondulée', 'unité', 'Bois et toiture'],
      ['Contreplaqué', 'unité', 'Bois et toiture'],
      ['Planche', 'unité', 'Bois et toiture'],
      ['Chevron', 'unité', 'Bois et toiture'],
      ['Peinture à eau', 'unité', 'Peinture'],
      ['Peinture à huile', 'unité', 'Peinture'],
      ['Diluant', 'L', 'Peinture'],
      ['Pinceau', 'unité', 'Peinture'],
      ['Rouleau à peinture', 'unité', 'Peinture'],
      ['Mastic', 'unité', 'Peinture'],
      ['Colle à bois', 'unité', 'Peinture'],
      ['Tuyau PVC', 'm', 'Plomberie'],
      ['Coude PVC', 'unité', 'Plomberie'],
      ['Robinet', 'unité', 'Plomberie'],
      ['Ruban d’étanchéité', 'rouleau', 'Plomberie'],
      ['Câble électrique', 'm', 'Électricité'],
      ['Interrupteur', 'unité', 'Électricité'],
      ['Prise de courant', 'unité', 'Électricité'],
      ['Ampoule LED', 'unité', 'Électricité'],
      ['Douille', 'unité', 'Électricité'],
      ['Disjoncteur', 'unité', 'Électricité'],
      ['Ruban isolant', 'rouleau', 'Électricité'],
      ['Rallonge électrique', 'unité', 'Électricité'],
      ['Cadenas', 'unité', 'Serrurerie'],
      ['Serrure', 'unité', 'Serrurerie'],
      ['Charnières', 'paire', 'Serrurerie'],
      ['Marteau', 'unité', 'Outillage'],
      ['Tournevis', 'unité', 'Outillage'],
      ['Pince', 'unité', 'Outillage'],
      ['Mètre ruban', 'unité', 'Outillage'],
      ['Scie à métaux', 'unité', 'Outillage'],
      ['Gants de travail', 'paire', 'Outillage'],
      ['Corde', 'm', 'Divers'],
      ['Bâche', 'm', 'Divers'],
    ]),
  },
  {
    id: 'vetements',
    libelle: 'Boutique de vêtements',
    articles: liste([
      ['T-shirt homme', 'unité', 'Homme'],
      ['Chemise homme', 'unité', 'Homme'],
      ['Pantalon homme', 'unité', 'Homme'],
      ['Jean homme', 'unité', 'Homme'],
      ['Short homme', 'unité', 'Homme'],
      ['Costume', 'unité', 'Homme'],
      ['Veste', 'unité', 'Homme'],
      ['Sous-vêtement homme', 'unité', 'Homme'],
      ['T-shirt femme', 'unité', 'Femme'],
      ['Chemisier', 'unité', 'Femme'],
      ['Robe', 'unité', 'Femme'],
      ['Jupe', 'unité', 'Femme'],
      ['Jean femme', 'unité', 'Femme'],
      ['Ensemble femme', 'unité', 'Femme'],
      ['Culotte', 'unité', 'Femme'],
      ['Soutien-gorge', 'unité', 'Femme'],
      ['Ensemble enfant', 'unité', 'Enfant'],
      ['T-shirt enfant', 'unité', 'Enfant'],
      ['Robe enfant', 'unité', 'Enfant'],
      ['Body bébé', 'unité', 'Enfant'],
      ['Pyjama enfant', 'unité', 'Enfant'],
      ['Uniforme scolaire', 'unité', 'Enfant'],
      ['Pagne (6 yards)', 'unité', 'Tissus'],
      ['Tissu wax', 'm', 'Tissus'],
      ['Tissu bazin', 'm', 'Tissus'],
      ['Chaussures homme', 'paire', 'Chaussures'],
      ['Chaussures femme', 'paire', 'Chaussures'],
      ['Chaussures enfant', 'paire', 'Chaussures'],
      ['Baskets', 'paire', 'Chaussures'],
      ['Sandales', 'paire', 'Chaussures'],
      ['Babouches', 'paire', 'Chaussures'],
      ['Chaussettes', 'paire', 'Chaussures'],
      ['Ceinture', 'unité', 'Accessoires'],
      ['Casquette', 'unité', 'Accessoires'],
      ['Chapeau', 'unité', 'Accessoires'],
      ['Foulard', 'unité', 'Accessoires'],
      ['Cravate', 'unité', 'Accessoires'],
      ['Sac à main', 'unité', 'Accessoires'],
      ['Portefeuille', 'unité', 'Accessoires'],
      ['Lunettes de soleil', 'unité', 'Accessoires'],
    ]),
  },
  {
    id: 'beaute',
    libelle: 'Cosmétique / beauté',
    articles: liste([
      ['Lait corporel', 'unité', 'Soins du corps'],
      ['Crème pour le visage', 'unité', 'Soins du corps'],
      ['Savon de toilette', 'unité', 'Soins du corps'],
      ['Gel douche', 'unité', 'Soins du corps'],
      ['Beurre de karité', 'unité', 'Soins du corps'],
      ['Huile de coco', 'bouteille', 'Soins du corps'],
      ['Déodorant', 'unité', 'Soins du corps'],
      ['Gommage', 'unité', 'Soins du corps'],
      ['Shampooing', 'bouteille', 'Cheveux'],
      ['Après-shampooing', 'bouteille', 'Cheveux'],
      ['Huile capillaire', 'bouteille', 'Cheveux'],
      ['Crème défrisante', 'unité', 'Cheveux'],
      ['Gel coiffant', 'unité', 'Cheveux'],
      ['Mèches', 'paquet', 'Cheveux'],
      ['Perruque', 'unité', 'Cheveux'],
      ['Peigne', 'unité', 'Cheveux'],
      ['Brosse à cheveux', 'unité', 'Cheveux'],
      ['Pinces à cheveux', 'paquet', 'Cheveux'],
      ['Élastiques à cheveux', 'paquet', 'Cheveux'],
      ['Henné', 'sachet', 'Cheveux'],
      ['Fond de teint', 'unité', 'Maquillage'],
      ['Poudre pour le visage', 'unité', 'Maquillage'],
      ['Rouge à lèvres', 'unité', 'Maquillage'],
      ['Mascara', 'unité', 'Maquillage'],
      ['Crayon pour les yeux', 'unité', 'Maquillage'],
      ['Fard à paupières', 'unité', 'Maquillage'],
      ['Démaquillant', 'bouteille', 'Maquillage'],
      ['Coton démaquillant', 'paquet', 'Maquillage'],
      ['Vernis à ongles', 'unité', 'Ongles'],
      ['Dissolvant', 'bouteille', 'Ongles'],
      ['Faux ongles', 'boîte', 'Ongles'],
      ['Colle à ongles', 'unité', 'Ongles'],
      ['Lime à ongles', 'unité', 'Ongles'],
      ['Eau de parfum', 'bouteille', 'Parfums'],
      ['Eau de toilette', 'bouteille', 'Parfums'],
      ['Parfum d’ambiance', 'unité', 'Parfums'],
      ['Trousse de maquillage', 'unité', 'Accessoires'],
      ['Miroir de poche', 'unité', 'Accessoires'],
    ]),
  },
  {
    id: 'parapharmacie',
    libelle: 'Pharmacie / parapharmacie (hygiène, sans médicament)',
    articles: liste([
      ['Brosse à dents', 'unité', 'Hygiène bucco-dentaire'],
      ['Dentifrice', 'unité', 'Hygiène bucco-dentaire'],
      ['Bain de bouche', 'bouteille', 'Hygiène bucco-dentaire'],
      ['Fil dentaire', 'unité', 'Hygiène bucco-dentaire'],
      ['Savon doux', 'unité', 'Hygiène'],
      ['Gel hydroalcoolique', 'bouteille', 'Hygiène'],
      ['Mouchoirs en papier', 'paquet', 'Hygiène'],
      ['Lingettes nettoyantes', 'paquet', 'Hygiène'],
      ['Rasoirs jetables', 'paquet', 'Hygiène'],
      ['Mousse à raser', 'unité', 'Hygiène'],
      ['Coupe-ongles', 'unité', 'Hygiène'],
      ['Serviettes hygiéniques', 'paquet', 'Hygiène féminine'],
      ['Protège-slips', 'paquet', 'Hygiène féminine'],
      ['Tampons', 'boîte', 'Hygiène féminine'],
      ['Préservatifs', 'boîte', 'Hygiène intime'],
      ['Couches bébé', 'paquet', 'Bébé'],
      ['Lingettes bébé', 'paquet', 'Bébé'],
      ['Biberon', 'unité', 'Bébé'],
      ['Tétine', 'unité', 'Bébé'],
      ['Lait de toilette bébé', 'bouteille', 'Bébé'],
      ['Savon bébé', 'unité', 'Bébé'],
      ['Coton-tiges', 'boîte', 'Bébé'],
      ['Crème hydratante', 'unité', 'Soins de la peau'],
      ['Crème solaire', 'unité', 'Soins de la peau'],
      ['Baume à lèvres', 'unité', 'Soins de la peau'],
      ['Lait corporel', 'unité', 'Soins de la peau'],
      ['Coton hydrophile', 'paquet', 'Petit matériel'],
      ['Compresses stériles', 'boîte', 'Petit matériel'],
      ['Pansements adhésifs', 'boîte', 'Petit matériel'],
      ['Bande de gaze', 'rouleau', 'Petit matériel'],
      ['Sparadrap', 'rouleau', 'Petit matériel'],
      ['Thermomètre', 'unité', 'Petit matériel'],
      ['Masques jetables', 'boîte', 'Petit matériel'],
      ['Gants d’examen', 'boîte', 'Petit matériel'],
      ['Moustiquaire', 'unité', 'Maison'],
      ['Répulsif anti-moustiques', 'unité', 'Maison'],
    ]),
  },
];

// Lignes du tableau « Ajouter plusieurs articles » à partir d'un modèle (prix vides à remplir).
export function lignesDuModele(id) {
  const modele = MODELES.find((m) => m.id === id);
  if (!modele) return [];
  return modele.articles.map((a) => ({ nom: a.nom, prix_vente: '', cout_achat: '', unite: a.unite, categorie: a.categorie, stock_initial: '' }));
}
